### PR TITLE
Fix tag feature

### LINKED ISSUE #59: Tag - updates
- toString() changes based on the ENUM of the tag

### PR DESCRIPTION
**Pull request by minghowC**
Fix the issue of tag attribute accepting random attribute to only "NR, OA, I, R, O", fix #59 of toString() issue.

_Bug 1 - Reject non-enums values_
Screenshot 2024-03-25 at 13 48 51

_Bug 2 - ToString() Outputs Full Value_
Screenshot 2024-03-25 at 14 38 43

Latest - merge successfully from the previous updates to F14-1/tp.

PS: **Passed TagTest.java, would like a second opinion?** Saw that some other test cases didn't pass, is it expected "305 tests completed, 96 failed"?

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Tag.java [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+    // Method to find a tag by string
+    public static Tags fromString(String input) {
+        for (Tags tag : Tags.values()) {
+            if (tag.name().equalsIgnoreCase(input) || tag.descriptiveName.equalsIgnoreCase(input)) {
+                return tag;
+            }
+        }
+        throw new IllegalArgumentException("Invalid tag: " + input);
+    }
+}
```
Comment (Jawad280) [inline src/main/java/seedu/address/model/person/Tag.java:38]: Good use of enums here ! I like the use of methods to check the validity as well as retrieving the tags ! LGTM 👍🏾

File: src/main/java/seedu/address/model/person/Tag.java [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+    public static boolean isValidTag(String input) {
+        return Tags.isValidTag(input);
+    }
+
+    /*
+     * Function overloading - isValidTag(String) & isValidTag(Tag)
+     */
+    public static boolean isValidTag(Tag tag) {
+        return Tags.isValidTag(tag.getTagName());
+    }
```
Comment (Jawad280) [inline src/main/java/seedu/address/model/person/Tag.java:96]: I like the overloading of isValidTag to tackle both String-type inputs as well as Tag-type inputs. LGTM 👍🏾

**Review by Jawad280 — COMMENTED** [review]
In general, great job in implementing the Tags as enums and providing restrictions when adding tags ! Code looks neat, clean and is easy to follow. LGTM 👍🏾
